### PR TITLE
Connect alert manager to auto-heal

### PR DESCRIPTION
**Pull request by jhernand**
This patch modifies the Prometheus alert manager configuration file so
that it sends alert notifications to the auto-heal service.

### CODE REVIEW

**Comment by jhernand** [comment]
@ironcladlou, @aweiteka, @cben, @zgalor please review.

The role that deploys the `autoheal` service is added in #12.

**Comment by ironcladlou** [comment]
I thought receivers were to be defined on a per-route basis, but I think I understand why you're going this direction given the current design of the autoheal bit which itself owns the mapping of an alert to an autoheal (implying all alerts would flow through auto-heal and be filtered). We should probably nail down a decision on where exactly the mapping between an alert and an autoheal receiver should live.

For example, would we expect the node team to update the autoheal component configuration? Or add metadata (annotations) to their alert rule? Or something else? I now see that the answer to that question will have effects on other pieces you're working on.

**Comment by jhernand** [comment]
The per-route configuration can contain the _name_ of the receiver, but first it has to be configure globally, once, to specify the webhook, at least that is my understanding. That is what this change is intended for. We will need other changes to use this receiver in the appropriate routes.

**Comment by ironcladlou** [comment]
>The per-route configuration can contain the name of the receiver, but first it has to be configure globally, once, to specify the webhook, at least that is my understanding. That is what this change is intended for. We will need other changes to use this receiver in the appropriate routes.

This prompted me to look much more closely at the docs and it seems you're quite correct... this helps me better understand your intent. Thank you!

**Pull request merged**
