### PR TITLE
Move scripts to hack dir

### PR DESCRIPTION
**Pull request by aweiteka**
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>

### CODE REVIEW

**Comment by aweiteka** [comment]
@ironcladlou I tested this from the base dir of the role.

**Comment by aweiteka** [comment]
FYI, this is in advance of making this a "proper" ansible role. Everything in the hack dir will be ignored by ansible. Ansible will use what's in tasks/, defaults/, vars/. The files/ dir will be common to the local dev hack use case in the short term.

**Comment by ironcladlou** [comment]
@aweiteka can you rebase? https://github.com/ironcladlou/openshift-ansible/pull/7 conflicted

**Comment by ironcladlou** [comment]
LGTM, thanks

**Pull request merged**
